a=float(input("enter the first number:"))
b=float(input("enter the second number:"))
c=float(input("enter the third number:"))
d=float(input("enter the fourth number:"))
e=float(input("enter the fifth number:"))
f=float(input("enter the sixth number:"))
print("sum:",a+b+c+d+e+f)